import type { HotspotPage } from "../entities/HotspotPage";

const HOTSPOT_DATA: HotspotPage = {
  region: "Jawa Barat",
  regionCode: "ID",
  center: [-6.9, 107.5],
  defaultHotspotId: "braga",
  regionStats: {
    activePhotographers: 14,
    momentsCapturedToday: 386,
    goldenHourTime: "17:42",
    goldenHourLocation: "Bandung",
  },
  activePhotographers: [
    {
      id: "1",
      name: "Sari",
      avatarUrl:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&q=70&auto=format&fit=crop",
    },
    {
      id: "2",
      name: "Reza",
      avatarUrl:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=70&auto=format&fit=crop",
    },
    {
      id: "3",
      name: "Alya",
      avatarUrl:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&q=70&auto=format&fit=crop",
    },
  ],
  feedMoments: [
    {
      id: "1",
      imageUrl:
        "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=300&q=80&auto=format&fit=crop",
      timeAgo: "2 min ago",
      caption: "A red jacket pausing under Braga's old colonial awnings.",
      photographerName: "Sari Pradipta",
      time: "17:42",
      tags: ["red", "braga", "on foot"],
    },
    {
      id: "2",
      imageUrl:
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=300&q=80&auto=format&fit=crop",
      timeAgo: "5 min ago",
      caption: "A vintage Vespa parked in the gold light, plate D · 1428 · NA.",
      photographerName: "Reza Ardiansyah",
      time: "17:39",
      tags: ["vespa", "silver", "D·1428"],
    },
    {
      id: "3",
      imageUrl:
        "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=300&q=80&auto=format&fit=crop",
      timeAgo: "7 min ago",
      caption: "A cyclist crossing the Braga tracks, almost smiling.",
      photographerName: "Alya Permatasari",
      time: "17:37",
      tags: ["bicycle", "commute"],
    },
    {
      id: "4",
      imageUrl:
        "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=300&q=80&auto=format&fit=crop",
      timeAgo: "10 min ago",
      caption: "An angkot exhaling its passengers into the warm afternoon.",
      photographerName: "Sari Pradipta",
      time: "17:34",
      tags: ["angkot", "crowd"],
    },
    {
      id: "5",
      imageUrl:
        "https://images.unsplash.com/photo-1551913902-c92207136625?w=300&q=80&auto=format&fit=crop",
      timeAgo: "13 min ago",
      caption: "Long hair, a steady stride — a Tuesday with somewhere to be.",
      photographerName: "Reza Ardiansyah",
      time: "17:31",
      tags: ["person", "long hair"],
    },
    {
      id: "6",
      imageUrl:
        "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=300&q=80&auto=format&fit=crop",
      timeAgo: "15 min ago",
      caption: "Braga's slow breath between passing cars.",
      photographerName: "Alya Permatasari",
      time: "17:29",
      tags: ["avenue", "quiet"],
    },
  ],
  hotspots: [
    {
      id: "braga",
      name: "Braga, Bandung",
      lat: -6.9175,
      lng: 107.6098,
      count: 48,
      level: "hot",
      title: "Braga, Bandung — <em>just now</em>.",
      meta: "Three photographers are quietly working the colonial stretch of Jalan Braga — golden hour folding into the awnings.",
      active: 3,
      last15: 9,
      total: 48,
    },
    {
      id: "asia-afrika",
      name: "Asia Afrika",
      lat: -6.9217,
      lng: 107.6094,
      count: 34,
      level: "hot",
      title: "Asia Afrika, Bandung — <em>warming up</em>.",
      meta: "Heritage façades, slow traffic. Two photographers between Hotel Savoy Homann and Alun-Alun.",
      active: 2,
      last15: 7,
      total: 34,
    },
    {
      id: "dago",
      name: "Dago",
      lat: -6.8852,
      lng: 107.6131,
      count: 22,
      level: "warm",
      title: "Dago — <em>café-side</em>.",
      meta: "A quieter run uphill — late lunch crowd, motorbikes parked in rows along Ir. H. Juanda.",
      active: 2,
      last15: 5,
      total: 22,
    },
    {
      id: "lembang",
      name: "Lembang",
      lat: -6.8125,
      lng: 107.6172,
      count: 18,
      level: "warm",
      title: "Lembang — <em>cool light</em>.",
      meta: "Mountain air, mist drifting off the strawberry fields. One photographer working the market road.",
      active: 1,
      last15: 4,
      total: 18,
    },
    {
      id: "cihampelas",
      name: "Cihampelas",
      lat: -6.895,
      lng: 107.6045,
      count: 14,
      level: "warm",
      title: "Cihampelas — <em>almost evening</em>.",
      meta: "Skywalk under sodium light, denim shops blinking on. One photographer pacing the bridge.",
      active: 1,
      last15: 3,
      total: 14,
    },
    {
      id: "kebon-raya",
      name: "Kebun Raya, Bogor",
      lat: -6.5971,
      lng: 106.799,
      count: 21,
      level: "warm",
      title: "Kebun Raya, Bogor — <em>green and hush</em>.",
      meta: "Botanical garden in late light. Two photographers at the orchid house entrance.",
      active: 2,
      last15: 5,
      total: 21,
    },
    {
      id: "puncak",
      name: "Puncak Pass",
      lat: -6.7,
      lng: 106.9833,
      count: 11,
      level: "warm",
      title: "Puncak Pass — <em>tea slope evening</em>.",
      meta: "Tea hills, motorbikes coasting through fog. One photographer at the lookout.",
      active: 1,
      last15: 2,
      total: 11,
    },
    {
      id: "bekasi",
      name: "Bekasi Centro",
      lat: -6.2383,
      lng: 106.9756,
      count: 9,
      level: "quiet",
      title: "Bekasi Centro — <em>quiet today</em>.",
      meta: "A handful of frames came in this afternoon. Worth checking again at dusk.",
      active: 0,
      last15: 1,
      total: 9,
    },
    {
      id: "cirebon",
      name: "Cirebon Old Town",
      lat: -6.732,
      lng: 108.5523,
      count: 7,
      level: "quiet",
      title: "Cirebon Old Town — <em>almost still</em>.",
      meta: "Coastal calm. A few frames from the kraton this morning.",
      active: 0,
      last15: 0,
      total: 7,
    },
    {
      id: "sukabumi",
      name: "Sukabumi",
      lat: -6.9277,
      lng: 106.93,
      count: 5,
      level: "quiet",
      title: "Sukabumi — <em>sleepy outskirts</em>.",
      meta: "Three frames came in this morning — none recent.",
      active: 0,
      last15: 0,
      total: 5,
    },
    {
      id: "depok",
      name: "Margonda, Depok",
      lat: -6.3927,
      lng: 106.8224,
      count: 6,
      level: "quiet",
      title: "Margonda, Depok — <em>weekday hush</em>.",
      meta: "Long shadows across the campus blocks. A handful of moments earlier.",
      active: 0,
      last15: 1,
      total: 6,
    },
    {
      id: "tasik",
      name: "Tasikmalaya",
      lat: -7.3274,
      lng: 108.2207,
      count: 4,
      level: "quiet",
      title: "Tasikmalaya — <em>far edge</em>.",
      meta: "Quiet streets near the alun-alun. Worth a visit on the weekend.",
      active: 0,
      last15: 0,
      total: 4,
    },
  ],
};

export function getHotspotPageData(): HotspotPage {
  return HOTSPOT_DATA;
}
