import { type PhotographersPage } from "../entities/PhotographersPage";

const sharedThumbs = [
  "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=300&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1551913902-c92207136625?w=300&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=300&q=80&auto=format&fit=crop",
] as const;

export function getPhotographersPageContent(): PhotographersPage {
  return {
    hero: {
      eyebrow: "The directory · 142 photographers · Indonesia",
      headline: "Meet the eyes",
      headlineEmphasis: "behind the lens",
      description:
        "Independent street photographers, working specific corners of specific cities. Browse their portfolios, read their philosophies, and book a private session on the streets they know best.",
      stats: [
        { value: "142", label: "Photographers in residence", emphasized: true },
        { value: "38", label: "Cities covered" },
        { value: "4.9", label: "Avg session rating" },
      ],
    },
    filters: [
      { label: "All", count: "142" },
      { label: "Bandung", count: "34" },
      { label: "Jakarta", count: "52" },
      { label: "Bogor", count: "14" },
      { label: "Bali", count: "22" },
      { label: "Surabaya", count: "12" },
      { label: "Yogya", count: "8" },
    ],
    visibleCountLabel: "Showing 6 of 142",
    sortLabel: "Most active this week",
    photographers: [
      {
        slug: "sari-pradipta",
        name: "Sari Pradipta",
        spec: "Bandung · Braga · Asia Afrika",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80&auto=format&fit=crop",
        isLive: true,
        ratingStars: "★★★★★",
        ratingMeta: "4.96 · 218",
        quote: "I photograph Braga at golden hour, when the colonial awnings turn copper.",
        thumbnails: [...sharedThumbs],
        tags: ["Heritage", "Golden hour", "Documentary"],
        momentsCaptured: "4,820",
        sessionsBooked: "218",
        hourlyRate: "Rp 450k",
      },
      {
        slug: "reza-ardiansyah",
        name: "Reza Ardiansyah",
        spec: "Jakarta · Sudirman · GBK",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80&auto=format&fit=crop",
        ratingStars: "★★★★★",
        ratingMeta: "4.92 · 314",
        quote: "The Sudirman crowd has a rhythm. I just try to be standing in the right second.",
        thumbnails: [
          "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=300&q=80&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=300&q=80&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=300&q=80&auto=format&fit=crop",
        ],
        tags: ["Sport", "Run clubs", "Motorbike"],
        momentsCaptured: "7,140",
        sessionsBooked: "314",
        hourlyRate: "Rp 600k",
      },
      {
        slug: "alya-permatasari",
        name: "Alya Permatasari",
        spec: "Bandung · Dago · Cihampelas",
        avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80&auto=format&fit=crop",
        isLive: true,
        ratingStars: "★★★★★",
        ratingMeta: "4.88 · 142",
        quote: "Late light up Dago when the warungs flicker on — that's when the city softens.",
        thumbnails: [
          "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=300&q=80&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=300&q=80&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=300&q=80&auto=format&fit=crop",
        ],
        tags: ["Café culture", "Vespa", "Editorial"],
        momentsCaptured: "3,210",
        sessionsBooked: "142",
        hourlyRate: "Rp 380k",
      },
      {
        slug: "bagus-wirawan",
        name: "Bagus Wirawan",
        spec: "Yogyakarta · Malioboro · Kotagede",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80&auto=format&fit=crop",
        ratingStars: "★★★★",
        mutedStars: "★",
        ratingMeta: "4.81 · 96",
        quote: "Becak drivers, silver-smiths, the nightly andong line — Yogya's slow theatre.",
        thumbnails: [
          sharedThumbs[0],
          sharedThumbs[2],
          "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=300&q=80&auto=format&fit=crop",
        ],
        tags: ["Heritage", "Black & white", "Slow shutter"],
        momentsCaptured: "2,180",
        sessionsBooked: "96",
        hourlyRate: "Rp 320k",
      },
      {
        slug: "komang-suarya",
        name: "Komang Suarya",
        spec: "Bali · Canggu · Ubud",
        avatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80&auto=format&fit=crop",
        isLive: true,
        ratingStars: "★★★★★",
        ratingMeta: "4.94 · 271",
        quote: "I work the rice-paddy roads at dawn. Mopeds. Mist. Old men in sarongs.",
        thumbnails: [
          "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=300&q=80&auto=format&fit=crop",
          sharedThumbs[1],
          "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=300&q=80&auto=format&fit=crop",
        ],
        tags: ["Dawn", "Travel", "Ritual"],
        momentsCaptured: "5,640",
        sessionsBooked: "271",
        hourlyRate: "Rp 520k",
      },
      {
        slug: "tessa-kuswandi",
        name: "Tessa Kuswandi",
        spec: "Surabaya · Tunjungan · Old Town",
        avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80&auto=format&fit=crop",
        ratingStars: "★★★★★",
        ratingMeta: "4.90 · 124",
        quote: "Surabaya's old quarter is mostly forgotten. I make a case for it, frame by frame.",
        thumbnails: [
          "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=300&q=80&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=300&q=80&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=300&q=80&auto=format&fit=crop",
        ],
        tags: ["Architecture", "Family", "Editorial"],
        momentsCaptured: "2,980",
        sessionsBooked: "124",
        hourlyRate: "Rp 420k",
      },
    ],
    booking: {
      eyebrow: "Private booking · simple as a postcard",
      headline: "Book a session.",
      headlineEmphasis: "Walk a street.",
      description:
        "Choose a photographer, a window of light, and a stretch of city. They'll meet you on the corner. Ninety minutes later, you'll have a roll of frames you'd never have made on your phone.",
      quote:
        "She was patient. We walked Braga twice. The third time around, the light caught a man arguing with a parking attendant and I have it forever now.",
      quoteBy: "— Adit R., on a session with Sari, March 2026",
      sessionTypes: ["Personal", "Family", "Vehicle", "Event"],
      timeSlots: [
        { label: "06:30 dawn", disabled: true },
        { label: "09:00 morning" },
        { label: "12:30 midday" },
        { label: "17:00 golden hour" },
        { label: "18:30 dusk" },
        { label: "21:00 night", disabled: true },
      ],
      locations: [
        "Jalan Braga · colonial stretch",
        "Asia Afrika · Hotel Savoy area",
        "Alun-Alun · old market",
        "Open to suggestion · we'll plan together",
      ],
      brief:
        "A walk for two. We're celebrating my parents' 35th — they grew up around Braga. Documentary style. Quiet, no posing. We'll come dressed in something they'd have worn in 1991.",
    },
  };
}
